Console.WriteLine("Hello, Tux!");
// HOLY FUCK IT WAS AWFUL INSTALLING .NET ON LINUX!!! I JUST WANTED TO RUN A FILE LOOSELY BUT I GUESS ISN'T POSSIBLE
// WITHOUT USING MONO AND MONO COMPILES AS AN EXE FILE. JESUS CHRIST MAN.
